TypeError
Python 3.9.7: E:\Anaconda3\envs\imgproapp\python.exe
Sat Dec 25 20:37:46 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\gui\subgui_edit.py in apply(self=<gui.subgui_edit.Ui_SubWindow object>)
 1444             else:
 1445                 self.graphicsView.coverPixmap()
 1446                 self.graphicsView.CVdst.Q2CVimg(self.graphicsView.imQT)
 1447 
 1448         if self.graphicsView.CVdst.img is not None:
self = <gui.subgui_edit.Ui_SubWindow object>
self.graphicsView = <widgets.ImgView.ImgView object>
self.graphicsView.CVdst = <plugins.ipc.AppImg object>
self.graphicsView.CVdst.Q2CVimg = <bound method AppImg.Q2CVimg of <plugins.ipc.AppImg object>>
self.graphicsView.imQT = <PyQt5.QtGui.QImage object>

 E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\ipc.py in Q2CVimg(self=<plugins.ipc.AppImg object>, Qimg=<PyQt5.QtGui.QImage object>)
  118                         print(Qimg.sizeInBytes())
  119                         CVimg = None
  120                     CVimg = CVimg[..., ::-1]
  121 
  122             self.img = CVimg
CVimg = None
TypeError: 'NoneType' object is not subscriptable
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = ValueError('cannot reshape array of size 1326556 into shape (511,865)')
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object is not subscriptable",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\ipc.py", line 102, in Q2CVimg
    CVimg = array(ptr, dtype=uint8).reshape(temp_shape)
ValueError: cannot reshape array of size 1326556 into shape (511,865,4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\ipc.py", line 109, in Q2CVimg
    CVimg = array(ptr, dtype=uint8).reshape(temp_shape)
ValueError: cannot reshape array of size 1326556 into shape (511,865)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\gui\subgui_edit.py", line 1446, in apply
    self.graphicsView.CVdst.Q2CVimg(self.graphicsView.imQT)
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\ipc.py", line 120, in Q2CVimg
    CVimg = CVimg[..., ::-1]
TypeError: 'NoneType' object is not subscriptable

